set_property SRC_FILE_INFO {cfile:/media/vsuarez/elocaldata/SCRATCH/foboot/hw/build/gateware/top.xdc rfile:../top.xdc id:1 order:EARLY} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC C2 [get_ports cpu_reset]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E3 [get_ports clk100]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D10 [get_ports serial_tx]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A9 [get_ports serial_rx]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G13 [get_ports usb_d_p]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B11 [get_ports usb_d_n]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A11 [get_ports usb_pullup]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_clock -name clk100 -period 10.0 [get_nets clk100]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -group [get_clocks -include_generated_clocks -of [get_nets sys_clk]] -group [get_clocks -include_generated_clocks -of [get_nets soc_clkin]] -asynchronous
